### ISSUE TITLE
Error in lapply

### ISSUE THREAD

**Issue by josemss** [OscarGVelasco/ClusterFoldSimilarity#4]
Hi Oscar, I'm Jose.

When I run lapply to normalise, scale, etc. my seurat objects I get an error.
Code:
singlecell.object.list <- lapply(X = singlecell.object.list, FUN = function(x){
  x <- NormalizeData(x)
  x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 1000)
  x <- ScaleData(x,features = VariableFeatures(x))
  x <- RunPCA(x, features = VariableFeatures(object = x))
  x <- FindNeighbors(x, dims = seq(10))
  x <- FindClusters(x, resolution = 0.1)
})
Error:
Computing nearest neighbor graph
Computing SNN
Error in validityMethod(as(object, superClass)) : 
  object 'CsparseMatrix_validate' not found

Attached is my script.
Thanks.
[ClusterFoldSimilarity_GEO_datasets.txt](https://github.com/OscarGVelasco/ClusterFoldSimilarity/files/11529454/ClusterFoldSimilarity_GEO_datasets.txt)

**Comment by OscarGVelasco** [comment]
The whole algorithm has been changed with a new similarity metric formula and approach.
